###

GET http://localhost:8080/benchmark
###
POST http://localhost:8080/user/login
###
POST http://localhost:8080/user/submit
###
POST http://localhost:8080/user/login
###
POST http://localhost:8080/user/read
###
GET http://localhost:8080/user/testing/analytics